### ISSUE TITLE
Error At Line 26 And more

### ISSUE THREAD

**Issue by SchoolHacker3** [systematicat/hack-captive-portals#11]
Error:
./hack-captive.sh: line 26: iw: command not found
Device "dev" does not exist.
Device "dev" does not exist.
Device "dev" does not exist.
Exploring network in "" Wi-Fi hotspot.
Splitting up network / into smaller chunks.
No luck! Try again later or try another Wi-Fi hotspot.
Cannot find device "down"
"" is invalid lladdr.
Cannot find device "up"
Device "dev" does not exist.
Error: any valid prefix is expected rather than "".
Error: any valid address is expected rather than "via".

**Comment by EricCaverly** [comment]
Temporary fix is to replace `interface="$(ip -o -4 route show to default | awk '/dev/ {print $5}')"` with `interface="wlp0s20f3"`

Obviously this is not ideal but it works as a break-fix solution. Make sure to replace wlp0s20f3 with your interface name in the event it is not the same.

**Comment by EricCaverly** [comment]
Side note: You may want to increase the sleep time for better reliability if DHCP is a little slow. Line 102 `sleep 1`, I set  it to 10 but 20 may have an even better chance.
