### ISSUE TITLE
what version of ubuntu was this meant for I can't find the command ip did you mean ifconfig ipconfig or iwconfig

### ISSUE THREAD

**Issue by charlieporth1** [systematicat/hack-captive-portals#3]
what version of ubuntu was this meant for I can't find the command ip did you mean ifconfig ipconfig or iwconfig

**Comment by systematicat** [comment]
Hi @charlieporth1 
Script was tested with 16.04 
In your case try to install `iproute2` package. 
Also you need `sipcalc` and `nmap` for this script.
Cheers!

**Comment by charlieporth1** [comment]
How would I make this work on a mac?

**Comment by charlieporth1** [comment]
how would I make this work on a mac?
