### ISSUE TITLE
My School Wireless can't is inability ,i give you picture

### ISSUE THREAD

**Issue by goooglethink** [systematicat/hack-captive-portals#4]
i give you logs:
sudo ./hack.sh
Exploring network in "Wing" Wi-Fi hotspot.
Splitting up network 10.2.192.0/19 into smaller chunks.                                                  
Looking for active hosts in 10.2.192.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.193.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.194.0/24. Please wait.  
sudo ./hack.sh
Exploring network in "Wing" Wi-Fi hotspot.
Splitting up network 10.2.192.0/19 into smaller chunks.                                                  
Looking for active hosts in 10.2.192.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.193.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.194.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.195.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.196.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.197.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.198.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.199.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.200.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.201.0/24. Please wait.                                                  
Suitable hosts not found. Checking another network chunk.                                                
Looking for active hosts in 10.2.202.0/24. Please wait. 

==============================================
uname -a
Linux google 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux
==============================================

i from china guangdon foshan neusoft school

**Comment by systematicat** [comment]
RTFM!
