### ISSUE TITLE
Could you make this work for OSX too?

### ISSUE THREAD

**Issue by charlieporth1** [systematicat/hack-captive-portals#5]
I've done some work here [https://github.com/charlieporth1/hack-captive-portalsOSX](here)
I'm not entirely sure how this works on Ubuntu because my ubuntu machine doesn't have a wireless card maybe you and I could collaborate on making this work?

**Comment by systematicat** [comment]
Hi @charlieporth1 !
Thanx for your participation! 
I've started using macOS recently but I don't think it's a good idea to use `bash` in macOS for network interface configuration. It's not a "Mac way". 
If you know some ways how to do it natively and nice in macOS feel free to share with me. 
And then I'll dig it deeper. Maybe I'll rewrite `script` in native `Swift` app or something.

**Comment by charlieporth1** [comment]
I would recomend if you just started using OSX to inhance I would install a package manager e.g. `brew`"HomeBrew"  && `port` "MacPorts"  which make `bash` on OSX much better (I've been on Freebsd Ubuntu and Kali and I love linux and the CLI)
