### ISSUE TITLE
Would this be feasible to port to Windows?

### ISSUE THREAD

**Issue by e-t-l** [systematicat/hack-captive-portals#7]
Like the question says, would this work well on Windows (other than running a virtual machine with Linux)?

**Comment by e-t-l** [comment]
Just to follow up - Could this even be done with a VM, or would the virtualized OS be unable to change the host machine's MAC address?

**Comment by systematicat** [comment]
Hi e-t-l!
I have nothing with Windows. So idk. Use your common sense and pseudoscientific tries. Then report me back. Cheers.
