### ISSUE TITLE
Nethunter

### ISSUE THREAD

**Issue by AndraxBoy** [systematicat/hack-captive-portals#8]
Is it possible port to android this super script?![Screenshot_20200711-212144.jpg](https://user-images.githubusercontent.com/59309496/87231046-8a502e80-c3bc-11ea-89e9-1cca0b0c0c4d.jpg)

**Comment by TheRicky90** [comment]
try an external wifi card wo is supported by nethunter, i think it does not recognize the internal wifi chip whitout a wifi module patch..

**Comment by Assfugil** [comment]
Same error :( except i am not chroot but executing from /data/adb  and added the correct path to the required utilities as an alias at the start of the script.
